import type { Metadata } from "next";
// import "@styles/_global.scss";

export const metadata: Metadata = {
  title: "Excel Compare",
  // description: "Generated by create next app", TODO: add description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
